sever:
  port: 8081

spring:
  profiles:
    active: dev #默认为开发环境

mybatis:
  mapper-locations: classpath:mapper/*.xml #mapper配置文件
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名
  type-aliases-package: com.apriltechnology.achieveit.entity #添加返回类型所在包

jwt:
  tokenHeader: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer
